### PR TITLE
Adding help for effects/status

### LINKED ISSUE #7: Trying to get command-specifc help for effects/status throws a 500 error
If you send the following payload to Photons:

```
{
    "command": "help",
    "args": {
        "command": "effects/status"
    }
}
```

The following error is thrown:

```
2020-03-10 09:23:39,241 ERROR   whirlwind.request_handlers.base expected string or bytes-like object
Traceback (most recent call last):
  File "/project/.photons-interactor/lib/python3.8/site-packages/whirlwind/request_handlers/base.py", line 220, in put
    info["result"] = await self.do_put(*args, **kwargs)
  File "/project/.photons-interactor/lib/python3.8/site-packages/whirlwind/request_handlers/command.py", line 80, in do_put
    return await self.commander.executor(progress_cb, self).execute(path, j)
  File "/project/.photons-interactor/lib/python3.8/site-packages/whirlwind/commander.py", line 89, in execute
    return await command.execute()
  File "/project/photons_interactor/commander/commands/base.py", line 30, in execute
    doc = dedent(getattr(kls, "__help__", kls.__doc__))
  File "/usr/local/lib/python3.8/textwrap.py", line 430, in dedent
    text = _whitespace_only_re.sub('', text)
TypeError: expected string or bytes-like object
```

### PR DESCRIPTION
**Pull request by Djelibeybi**
Fixes #7.

Signed-off-by: Avi Miller <me@dje.li>

### CODE REVIEW

**Comment by delfick** [comment]
perfect, thanks :)

**Comment by delfick** [comment]
I'm in the process of cleaning up tile animation code, depending on how long that takes, I'll release a new version once that's done

**Comment by Djelibeybi** [comment]
All good. I'm planning on writing a blog post after I play with splatting and striping themes as part of starting an effect, so that'll take a couple of hours to play with anyway.

**Comment by delfick** [comment]
my change is a weekend or two away :p

**Pull request merged**
